# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividade',
            fields=[
                ('cod_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion', models.FloatField(blank=True, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Actividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aprobacione',
            fields=[
                ('cod_ok', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Aprobacione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignacione',
            fields=[
                ('cod_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Asignacione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atp',
            fields=[
                ('cod_atp', models.AutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Atp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudade',
            fields=[
                ('cod_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Ciudade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('cod_contratista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Contratista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('cod_diseno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Diseno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('cod_entregable', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_entregable', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Entregable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estacione',
            fields=[
                ('cod_station', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Estacione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cod_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('cod_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('referencia', models.IntegerField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Implementacione',
            fields=[
                ('cod_imp', models.AutoField(primary_key=True, serialize=False)),
                ('estimado', models.DateTimeField()),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Implementacione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operacione',
            fields=[
                ('cod_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Operacione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('cod_operadora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Operadora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('level', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Privilegio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('cod_region', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Regione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('cod_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoFactura',
            fields=[
                ('cod_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Tipo_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPo',
            fields=[
                ('cod_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField(blank=True, null=True)),
                ('modificado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tipo_PO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('cod_vendor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'Vendor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspeccione',
            fields=[
                ('cod_srvy', models.AutoField(primary_key=True)),
                ('cod_station', models.OneToOneField(db_column='cod_station', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Estacione')),
                ('estimada', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Inspeccione',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('cod_po', models.AutoField(primary_key=True)),
                ('num_tipo', models.IntegerField(blank=True, null=True)),
                ('cod_tipo', models.OneToOneField(db_column='cod_tipo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.TipoPo')),
                ('creado', models.DateTimeField()),
                ('modificado', models.DateTimeField()),
            ],
            options={
                'db_table': 'PO',
                'managed': False,
            },
        ),
    ]
